clc;
clear;
u=@(t)double(t>=0);
t=-2:0.1:3;
f1=t.*(u(t)-u(t-2));
f2=(t+1).*(u(t+1)-u(t-1));
f3=(1-t).*(u(1-t)-u(-1-t));
f4=(1-2*t).*(u(1-2*t)-u(-1-2*t));
subplot(2,2,4);
plot(t,f4,'DisplayName','f(1-2t)');
grid on;
legend('show');
subplot(2,2,3);
plot(t,f3,'DisplayName','f(1-t)');
grid on;
legend('show');
subplot(2,2,2);
plot(t,f2,'DisplayName','f(t+1)');
grid on;
legend('show');
subplot(2,2,1);
plot(t,f1,'DisplayName','f(t)');
grid on;
legend('show');