function Hd = getFilter_Bandstop
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 09-Jan-2023 17:54:04

N     = 30;   % Order
F3dB1 = 49;   % First
F3dB2 = 51;   % Second
Fs    = 500;  % Sampling Frequency

h = fdesign.bandstop('n,f3db1,f3db2', N, F3dB1, F3dB2, Fs);

Hd = design(h, 'butter', ...
    'SystemObject', true);
end

